import { TocItem } from './types';

export const TOTAL_PAGES = 656; 

// Based on the provided screenshots of the Table of Contents
export const TOC_DATA: TocItem[] = [
  { id: 1, title: "বিস্তারিত সূচীপত্র", page: 6 },
  { id: 2, title: "ইলম হাসিল করা সম্পর্কিত কথা", page: 37, section: "সূচনা" },
  { id: 3, title: "প্রথম অধ্যায়: ঈমান ও আকাইদ", page: 45, section: "ঈমান" },
  { id: 4, title: "আল্লাহর উপর ঈমান", page: 47, section: "ঈমান" },
  { id: 5, title: "তাকদীর সম্বন্ধে ঈমান", page: 54, section: "ঈমান" },
  { id: 6, title: "আল্লাহর ৯৯টি নাম", page: 56, section: "ঈমান" },
  { id: 7, title: "কেয়ামতের আলামত", page: 72, section: "ঈমান" },
  { id: 8, title: "মাজার ও পীর বুজুর্গ", page: 79, section: "ঈমান" },
  { id: 9, title: "দ্বিতীয় অধ্যায়: ইবাদাত", page: 113, section: "ইবাদাত" },
  { id: 10, title: "পবিত্রতা ও অজু", page: 113, section: "ইবাদাত" },
  { id: 11, title: "গোসলের মাসায়েল", page: 137, section: "ইবাদাত" },
  { id: 12, title: "তায়াম্মুম", page: 140, section: "ইবাদাত" },
  { id: 13, title: "হায়েয নেফাস", page: 144, section: "ইবাদাত" },
  { id: 14, title: "নামায", page: 176, section: "ইবাদাত" },
  { id: 15, title: "জুমুআর নামায", page: 208, section: "ইবাদাত" },
  { id: 16, title: "ঈদের নামায", page: 215, section: "ইবাদাত" },
  { id: 17, title: "জানাজার নামায", page: 515, section: "ইবাদাত" },
  { id: 18, title: "যাকাত", page: 260, section: "ইবাদাত" },
  { id: 19, title: "রোজা", page: 286, section: "ইবাদাত" },
  { id: 20, title: "হজ্জ", page: 280, section: "ইবাদাত" },
  { id: 21, title: "কুরবানী", page: 271, section: "ইবাদাত" },
  { id: 22, title: "তৃতীয় অধ্যায়: মুআমালাত", page: 359, section: "মুআমালাত" },
  { id: 23, title: "অর্থনীতি ও ব্যবসা", page: 361, section: "মুআমালাত" },
  { id: 24, title: "চাকুরী ও শ্রমনীতি", page: 378, section: "মুআমালাত" },
  { id: 25, title: "বিবাহ ও তালাক", page: 395, section: "মুআমালাত" },
  { id: 26, title: "মীরাছ বা উত্তরাধিকার", page: 409, section: "মুআমালাত" },
  { id: 27, title: "চতুর্থ অধ্যায়: মুআশারাত", page: 413, section: "মুআশারাত" },
  { id: 28, title: "পিতা-মাতা ও সন্তানের হক", page: 413, section: "মুআশারাত" },
  { id: 29, title: "স্বামী-স্ত্রীর অধিকার", page: 421, section: "মুআশারাত" },
  { id: 30, title: "আদব কায়দা ও শিষ্টাচার", page: 441, section: "মুআশারাত" },
  { id: 31, title: "পর্দার আহকাম", page: 329, section: "মুআশারাত" },
  { id: 32, title: "পোশাক-পরিচ্ছদ", page: 468, section: "মুআশারাত" },
  { id: 33, title: "পঞ্চম অধ্যায়: আখলাকিয়াত", page: 581, section: "আখলাকিয়াত" },
  { id: 34, title: "তাকওয়া ও সবর", page: 582, section: "আখলাকিয়াত" },
  { id: 35, title: "হিংসা ও গীবত", page: 598, section: "আখলাকিয়াত" },
  { id: 36, title: "তওবা ও এস্তেগফার", page: 625, section: "আখলাকিয়াত" },
  { id: 37, title: "তাজবীদ", page: 630, section: "বিবিধ" },
];